-- Autimex Reports — clientes consolidados e configuração efetiva por conta.
-- Migration aditiva: nenhum código/nome de sales_rows é alterado.
-- Execute depois de 0022_replace_period_on_reupload.sql.
-- Revisão: r4 — chat_recent_orders foi isolada na migration 0024.

CREATE OR REPLACE FUNCTION account_owner_for_user(p_user_id UUID)
RETURNS UUID
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE(
    (SELECT profile.leader_id FROM profiles profile WHERE profile.id = p_user_id),
    p_user_id
  );
$$;

CREATE OR REPLACE FUNCTION current_account_owner_id()
RETURNS UUID
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT account_owner_for_user(auth.uid());
$$;

CREATE OR REPLACE FUNCTION is_current_account_leader()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles profile
    WHERE profile.id = auth.uid()
      AND profile.role = 'leader'
      AND profile.leader_id IS NULL
  );
$$;

REVOKE ALL ON FUNCTION account_owner_for_user(UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION current_account_owner_id() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION is_current_account_leader() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION current_account_owner_id() TO authenticated;
GRANT EXECUTE ON FUNCTION is_current_account_leader() TO authenticated;

CREATE TABLE IF NOT EXISTS client_groups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_owner_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (CHAR_LENGTH(TRIM(name)) BETWEEN 2 AND 120),
  created_by UUID NOT NULL REFERENCES profiles(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (id, account_owner_id)
);

CREATE TABLE IF NOT EXISTS client_group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id UUID NOT NULL,
  account_owner_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  cod_cliente TEXT NOT NULL CHECK (CHAR_LENGTH(TRIM(cod_cliente)) BETWEEN 1 AND 160),
  nome_cliente TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT client_group_members_group_account_fkey
    FOREIGN KEY (group_id, account_owner_id)
    REFERENCES client_groups(id, account_owner_id)
    ON DELETE CASCADE,
  CONSTRAINT client_group_members_account_code_key
    UNIQUE (account_owner_id, cod_cliente),
  CONSTRAINT client_group_members_group_code_key
    UNIQUE (group_id, cod_cliente)
);

CREATE INDEX IF NOT EXISTS idx_client_groups_account_name
  ON client_groups(account_owner_id, name);
CREATE INDEX IF NOT EXISTS idx_client_group_members_group
  ON client_group_members(group_id, cod_cliente);

ALTER TABLE client_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_group_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS client_groups_read_account ON client_groups;
DROP POLICY IF EXISTS client_groups_write_leader ON client_groups;
DROP POLICY IF EXISTS client_group_members_read_account ON client_group_members;
DROP POLICY IF EXISTS client_group_members_write_leader ON client_group_members;

CREATE POLICY client_groups_read_account ON client_groups
  FOR SELECT TO authenticated
  USING (account_owner_id = current_account_owner_id());

CREATE POLICY client_groups_write_leader ON client_groups
  FOR ALL TO authenticated
  USING (account_owner_id = auth.uid() AND is_current_account_leader())
  WITH CHECK (
    account_owner_id = auth.uid()
    AND created_by = auth.uid()
    AND is_current_account_leader()
  );

CREATE POLICY client_group_members_read_account ON client_group_members
  FOR SELECT TO authenticated
  USING (account_owner_id = current_account_owner_id());

CREATE POLICY client_group_members_write_leader ON client_group_members
  FOR ALL TO authenticated
  USING (account_owner_id = auth.uid() AND is_current_account_leader())
  WITH CHECK (account_owner_id = auth.uid() AND is_current_account_leader());

GRANT SELECT ON client_groups TO authenticated;
GRANT SELECT ON client_group_members TO authenticated;

-- Compatibilidade para contas que configuraram relatórios pelo usuário de um
-- representante: o item mais recente é copiado para o líder apenas quando ele
-- ainda não possui o mesmo relatório/referência. As linhas antigas permanecem.
WITH representative_config AS (
  SELECT
    profile.leader_id AS account_owner_id,
    config.report_key,
    config.cod_referencia,
    config.categoria,
    config.label,
    config.sort_order,
    config.extra_data,
    config.created_at,
    ROW_NUMBER() OVER (
      PARTITION BY profile.leader_id, config.report_key, config.cod_referencia
      ORDER BY config.created_at DESC, config.id DESC
    ) AS preference
  FROM report_config_items config
  JOIN profiles profile ON profile.id = config.user_id
  WHERE profile.role = 'rep'
    AND profile.leader_id IS NOT NULL
    AND config.cod_referencia IS NOT NULL
)
INSERT INTO report_config_items (
  user_id, report_key, cod_referencia, categoria, label, sort_order, extra_data, created_at
)
SELECT
  account_owner_id, report_key, cod_referencia, categoria, label, sort_order, extra_data, created_at
FROM representative_config
WHERE preference = 1
ON CONFLICT (user_id, report_key, cod_referencia)
  WHERE cod_referencia IS NOT NULL
DO NOTHING;

-- Resolve uma chave canônica. Uma chave legada que já seja membro de grupo
-- também se expande para todos os membros, evitando resultados divergentes.
CREATE OR REPLACE FUNCTION resolve_client_codes(p_client_key TEXT)
RETURNS TABLE (cod_cliente TEXT)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_owner UUID := current_account_owner_id();
  v_group UUID;
BEGIN
  IF p_client_key IS NULL OR TRIM(p_client_key) = '' THEN
    RETURN;
  END IF;

  IF p_client_key ~* '^group:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' THEN
    v_group := SUBSTRING(p_client_key FROM 7)::UUID;
  ELSE
    SELECT member.group_id INTO v_group
    FROM client_group_members member
    WHERE member.account_owner_id = v_owner
      AND member.cod_cliente = p_client_key
    LIMIT 1;
  END IF;

  IF v_group IS NOT NULL THEN
    RETURN QUERY
      SELECT member.cod_cliente
      FROM client_group_members member
      WHERE member.account_owner_id = v_owner
        AND member.group_id = v_group
      ORDER BY member.cod_cliente;
  ELSE
    RETURN QUERY SELECT p_client_key;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION resolve_client_codes(TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION resolve_client_codes(TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION search_raw_clients(p_query TEXT DEFAULT '', p_limit INT DEFAULT 500)
RETURNS TABLE (cod_cliente TEXT, nome_cliente TEXT, group_id UUID, group_name TEXT)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION
    SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  ),
  raw AS (
    SELECT sales.cod_cliente, MAX(sales.nome_cliente) AS nome_cliente
    FROM sales_rows sales
    JOIN authorized_owners owner ON owner.user_id = sales.user_id
    WHERE TRIM(p_query) = ''
      OR LOWER(sales.cod_cliente) LIKE '%' || LOWER(TRIM(p_query)) || '%'
      OR LOWER(sales.nome_cliente) LIKE '%' || LOWER(TRIM(p_query)) || '%'
    GROUP BY sales.cod_cliente
  )
  SELECT raw.cod_cliente, raw.nome_cliente, member.group_id, group_row.name
  FROM raw
  LEFT JOIN client_group_members member
    ON member.account_owner_id = current_account_owner_id()
    AND member.cod_cliente = raw.cod_cliente
  LEFT JOIN client_groups group_row ON group_row.id = member.group_id
  ORDER BY raw.nome_cliente, raw.cod_cliente
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 500), 1), 1000);
$$;

CREATE OR REPLACE FUNCTION save_client_group(p_group_id UUID, p_name TEXT, p_codes TEXT[])
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_group_id UUID := p_group_id;
  v_codes TEXT[];
  v_code_count INT;
  v_existing_count INT;
BEGIN
  IF NOT is_current_account_leader() OR current_account_owner_id() <> auth.uid() THEN
    RAISE EXCEPTION 'Leader access required' USING ERRCODE = '42501';
  END IF;
  IF CHAR_LENGTH(TRIM(COALESCE(p_name, ''))) NOT BETWEEN 2 AND 120 THEN
    RAISE EXCEPTION 'Invalid group name' USING ERRCODE = '22023';
  END IF;

  SELECT ARRAY_AGG(code ORDER BY code), COUNT(*)
    INTO v_codes, v_code_count
  FROM (SELECT DISTINCT TRIM(value) AS code FROM UNNEST(COALESCE(p_codes, ARRAY[]::TEXT[])) value WHERE TRIM(value) <> '') normalized;

  IF v_code_count < 2 OR v_code_count > 100 THEN
    RAISE EXCEPTION 'A group must contain between 2 and 100 clients' USING ERRCODE = '22023';
  END IF;

  SELECT COUNT(DISTINCT sales.cod_cliente) INTO v_existing_count
  FROM sales_rows sales
  WHERE sales.cod_cliente = ANY(v_codes)
    AND (
      sales.user_id = auth.uid()
      OR sales.user_id IN (SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid())
    );
  IF v_existing_count <> v_code_count THEN
    RAISE EXCEPTION 'One or more clients are outside the account' USING ERRCODE = '42501';
  END IF;

  IF v_group_id IS NULL THEN
    INSERT INTO client_groups (account_owner_id, name, created_by)
    VALUES (auth.uid(), TRIM(p_name), auth.uid())
    RETURNING id INTO v_group_id;
  ELSE
    UPDATE client_groups
    SET name = TRIM(p_name), updated_at = NOW()
    WHERE id = v_group_id AND account_owner_id = auth.uid();
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Group not found' USING ERRCODE = 'P0002';
    END IF;
    DELETE FROM client_group_members WHERE group_id = v_group_id AND account_owner_id = auth.uid();
  END IF;

  INSERT INTO client_group_members (group_id, account_owner_id, cod_cliente, nome_cliente)
  SELECT
    v_group_id,
    auth.uid(),
    code,
    (
      SELECT MAX(sales.nome_cliente)
      FROM sales_rows sales
      WHERE sales.cod_cliente = code
        AND (
          sales.user_id = auth.uid()
          OR sales.user_id IN (SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid())
        )
    )
  FROM UNNEST(v_codes) code;

  RETURN v_group_id;
END;
$$;

CREATE OR REPLACE FUNCTION delete_client_group(p_group_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT is_current_account_leader() OR current_account_owner_id() <> auth.uid() THEN
    RAISE EXCEPTION 'Leader access required' USING ERRCODE = '42501';
  END IF;

  DELETE FROM client_groups
  WHERE id = p_group_id AND account_owner_id = auth.uid();
  RETURN FOUND;
END;
$$;

REVOKE ALL ON FUNCTION search_raw_clients(TEXT, INT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION save_client_group(UUID, TEXT, TEXT[]) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION delete_client_group(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION search_raw_clients(TEXT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION save_client_group(UUID, TEXT, TEXT[]) TO authenticated;
GRANT EXECUTE ON FUNCTION delete_client_group(UUID) TO authenticated;

-- Catálogo: grupos aparecem uma vez; membros deixam de aparecer isoladamente.
CREATE OR REPLACE FUNCTION search_clients(
  p_query TEXT DEFAULT '',
  p_limit INT DEFAULT 12,
  p_offset INT DEFAULT 0
)
RETURNS TABLE (cod_cliente TEXT, nome_cliente TEXT)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION
    SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  ),
  raw_clients AS (
    SELECT sales.cod_cliente, MAX(sales.nome_cliente) AS nome_cliente
    FROM sales_rows sales
    JOIN authorized_owners owner ON owner.user_id = sales.user_id
    GROUP BY sales.cod_cliente
  ),
  normalized AS (
    SELECT
      NULLIF(LOWER(TRIM(p_query)), '') AS query_text,
      NULLIF(REGEXP_REPLACE(LOWER(TRIM(p_query)), '[^a-z0-9]+', '', 'g'), '') AS query_compact,
      NULLIF(REGEXP_REPLACE(TRIM(p_query), '[^0-9]+', '', 'g'), '') AS query_digits
  ),
  options AS (
    SELECT
      'group:' || group_row.id::TEXT AS cod_cliente,
      group_row.name AS nome_cliente,
      group_row.name || ' ' || COALESCE(
        STRING_AGG(DISTINCT member.cod_cliente || ' ' || COALESCE(raw.nome_cliente, ''), ' '),
        ''
      ) AS search_text
    FROM client_groups group_row
    LEFT JOIN client_group_members member
      ON member.account_owner_id = group_row.account_owner_id
      AND member.group_id = group_row.id
    LEFT JOIN raw_clients raw ON raw.cod_cliente = member.cod_cliente
    WHERE group_row.account_owner_id = current_account_owner_id()
    GROUP BY group_row.id, group_row.name

    UNION ALL

    SELECT raw.cod_cliente, raw.nome_cliente, raw.cod_cliente || ' ' || raw.nome_cliente
    FROM raw_clients raw
    WHERE NOT EXISTS (
      SELECT 1 FROM client_group_members member
      WHERE member.account_owner_id = current_account_owner_id()
        AND member.cod_cliente = raw.cod_cliente
    )
  )
  SELECT option.cod_cliente, option.nome_cliente
  FROM options option
  CROSS JOIN normalized query
  WHERE query.query_text IS NULL
    OR LOWER(option.search_text) LIKE '%' || query.query_text || '%'
    OR REGEXP_REPLACE(LOWER(option.search_text), '[^a-z0-9]+', '', 'g') LIKE '%' || query.query_compact || '%'
    OR REGEXP_REPLACE(option.search_text, '[^0-9]+', '', 'g') LIKE '%' || query.query_digits || '%'
  ORDER BY
    CASE
      WHEN LOWER(option.cod_cliente) = query.query_text THEN 0
      WHEN LOWER(option.nome_cliente) = query.query_text THEN 1
      ELSE 2
    END,
    option.nome_cliente,
    option.cod_cliente
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 12), 1), 100)
  OFFSET GREATEST(COALESCE(p_offset, 0), 0);
$$;

REVOKE ALL ON FUNCTION search_clients(TEXT, INT, INT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION search_clients(TEXT, INT, INT) TO authenticated;

CREATE OR REPLACE FUNCTION tabela_dinamica_geral(
  p_ano INT,
  p_cod_cliente TEXT DEFAULT NULL,
  p_cod_referencia TEXT DEFAULT NULL,
  p_semestre INT DEFAULT NULL,
  p_descr_hist_financ TEXT DEFAULT NULL
)
RETURNS TABLE (ano SMALLINT, cod_cliente TEXT, nome_cliente TEXT, apelido TEXT, cod_referencia TEXT, descr_produto TEXT, jan NUMERIC, fev NUMERIC, mar NUMERIC, abr NUMERIC, mai NUMERIC, jun NUMERIC, jul NUMERIC, ago NUMERIC, set_ NUMERIC, out_ NUMERIC, nov NUMERIC, dez NUMERIC, total_ano NUMERIC, total_valor NUMERIC)
LANGUAGE SQL STABLE AS $$
  SELECT
    s.ano,
    COALESCE('group:' || g.id::TEXT, s.cod_cliente),
    COALESCE(g.name, MAX(s.nome_cliente)),
    CASE WHEN g.id IS NULL THEN MAX(s.apelido) ELSE NULL END,
    s.cod_referencia,
    MAX(s.descr_produto),
    SUM(CASE WHEN s.mes=1 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=2 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=3 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=4 THEN s.quantidade ELSE 0 END),
    SUM(CASE WHEN s.mes=5 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=6 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=7 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=8 THEN s.quantidade ELSE 0 END),
    SUM(CASE WHEN s.mes=9 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=10 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=11 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=12 THEN s.quantidade ELSE 0 END),
    SUM(s.quantidade), SUM(s.valor_total)
  FROM sales_rows s
  LEFT JOIN client_group_members m
    ON m.account_owner_id = current_account_owner_id() AND m.cod_cliente = s.cod_cliente
  LEFT JOIN client_groups g ON g.id = m.group_id
  WHERE s.ano = p_ano
    AND (p_cod_cliente IS NULL OR s.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code))
    AND (p_cod_referencia IS NULL OR s.cod_referencia = p_cod_referencia)
    AND (p_semestre IS NULL OR (p_semestre=1 AND s.mes BETWEEN 1 AND 6) OR (p_semestre=2 AND s.mes BETWEEN 7 AND 12))
    AND (p_descr_hist_financ IS NULL OR s.descr_hist_financ = p_descr_hist_financ)
  GROUP BY s.ano, COALESCE('group:' || g.id::TEXT, s.cod_cliente), g.id, g.name, s.cod_referencia
  ORDER BY COALESCE(g.name, MAX(s.nome_cliente)), s.cod_referencia;
$$;

CREATE OR REPLACE FUNCTION base_de_compra(p_ano INT, p_cod_cliente TEXT DEFAULT NULL, p_cod_referencia TEXT DEFAULT NULL, p_semestre INT DEFAULT NULL, p_descr_hist_financ TEXT DEFAULT NULL)
RETURNS TABLE (ano SMALLINT, cod_referencia TEXT, descr_produto TEXT, jan NUMERIC, fev NUMERIC, mar NUMERIC, abr NUMERIC, mai NUMERIC, jun NUMERIC, jul NUMERIC, ago NUMERIC, set_ NUMERIC, out_ NUMERIC, nov NUMERIC, dez NUMERIC, total_ano NUMERIC)
LANGUAGE SQL STABLE AS $$
  SELECT s.ano, s.cod_referencia, MAX(s.descr_produto),
    SUM(CASE WHEN s.mes=1 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=2 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=3 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=4 THEN s.quantidade ELSE 0 END),
    SUM(CASE WHEN s.mes=5 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=6 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=7 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=8 THEN s.quantidade ELSE 0 END),
    SUM(CASE WHEN s.mes=9 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=10 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=11 THEN s.quantidade ELSE 0 END), SUM(CASE WHEN s.mes=12 THEN s.quantidade ELSE 0 END), SUM(s.quantidade)
  FROM sales_rows s
  WHERE s.ano = p_ano
    AND (p_cod_cliente IS NULL OR s.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code))
    AND (p_cod_referencia IS NULL OR s.cod_referencia = p_cod_referencia)
    AND (p_semestre IS NULL OR (p_semestre=1 AND s.mes BETWEEN 1 AND 6) OR (p_semestre=2 AND s.mes BETWEEN 7 AND 12))
    AND (p_descr_hist_financ IS NULL OR s.descr_hist_financ = p_descr_hist_financ)
  GROUP BY s.ano, s.cod_referencia ORDER BY s.cod_referencia;
$$;

CREATE OR REPLACE FUNCTION dashboard_summary(p_ano INT DEFAULT NULL, p_cod_cliente TEXT DEFAULT NULL, p_cod_referencia TEXT DEFAULT NULL, p_semestre INT DEFAULT NULL, p_descr_hist_financ TEXT DEFAULT NULL)
RETURNS TABLE (total_pedidos BIGINT, total_faturado NUMERIC, num_clientes BIGINT, num_produtos BIGINT, total_unidades NUMERIC, data_inicio DATE, data_fim DATE, anos_disponiveis INT[])
LANGUAGE SQL STABLE AS $$
  SELECT
    COUNT(DISTINCT s.codigo_pedido),
    COALESCE(SUM(s.valor_total),0),
    COUNT(DISTINCT COALESCE('group:' || m.group_id::TEXT, s.cod_cliente)),
    COUNT(DISTINCT s.cod_referencia),
    COALESCE(SUM(s.quantidade),0),
    MIN(s.data_pedido), MAX(s.data_pedido),
    ARRAY(SELECT DISTINCT years.ano FROM sales_rows years ORDER BY years.ano)
  FROM sales_rows s
  LEFT JOIN client_group_members m
    ON m.account_owner_id = current_account_owner_id() AND m.cod_cliente = s.cod_cliente
  WHERE (p_ano IS NULL OR s.ano = p_ano)
    AND (p_cod_cliente IS NULL OR s.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code))
    AND (p_cod_referencia IS NULL OR s.cod_referencia = p_cod_referencia)
    AND (p_semestre IS NULL OR (p_semestre=1 AND s.mes BETWEEN 1 AND 6) OR (p_semestre=2 AND s.mes BETWEEN 7 AND 12))
    AND (p_descr_hist_financ IS NULL OR s.descr_hist_financ = p_descr_hist_financ);
$$;

CREATE OR REPLACE FUNCTION configured_report_rows(p_report_key TEXT, p_anos INT[], p_cod_cliente TEXT DEFAULT NULL, p_cod_referencia TEXT DEFAULT NULL, p_semestre INT DEFAULT NULL, p_descr_hist_financ TEXT DEFAULT NULL)
RETURNS TABLE (id BIGINT, sort_order INTEGER, cod_referencia TEXT, label TEXT, extra_data JSONB, totals_by_year JSONB)
LANGUAGE SQL STABLE AS $$
  SELECT c.id, c.sort_order, c.cod_referencia, COALESCE(c.label, MAX(s.descr_produto), c.cod_referencia), c.extra_data,
    COALESCE(jsonb_object_agg(s.ano::TEXT, s.qty) FILTER (WHERE s.ano IS NOT NULL), '{}'::JSONB)
  FROM report_config_items c
  LEFT JOIN (
    SELECT sr.cod_referencia, sr.ano, SUM(sr.quantidade) AS qty, MAX(sr.descr_produto) AS descr_produto
    FROM sales_rows sr
    WHERE sr.ano = ANY(p_anos)
      AND (p_cod_cliente IS NULL OR sr.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code))
      AND (p_cod_referencia IS NULL OR sr.cod_referencia = p_cod_referencia)
      AND (p_semestre IS NULL OR (p_semestre=1 AND sr.mes BETWEEN 1 AND 6) OR (p_semestre=2 AND sr.mes BETWEEN 7 AND 12))
      AND (p_descr_hist_financ IS NULL OR sr.descr_hist_financ = p_descr_hist_financ)
    GROUP BY sr.cod_referencia, sr.ano
  ) s ON s.cod_referencia = c.cod_referencia
  WHERE c.report_key = p_report_key
  GROUP BY c.id,c.sort_order,c.cod_referencia,c.label,c.extra_data
  ORDER BY c.sort_order,c.cod_referencia;
$$;

CREATE OR REPLACE FUNCTION geral(p_ano INT, p_cod_cliente TEXT DEFAULT NULL, p_cod_referencia TEXT DEFAULT NULL, p_semestre INT DEFAULT NULL, p_descr_hist_financ TEXT DEFAULT NULL)
RETURNS TABLE (id BIGINT, sort_order INTEGER, categoria TEXT, cod_referencia TEXT, label TEXT, extra_data JSONB, jan NUMERIC, fev NUMERIC, mar NUMERIC, abr NUMERIC, mai NUMERIC, jun NUMERIC, jul NUMERIC, ago NUMERIC, set_ NUMERIC, out_ NUMERIC, nov NUMERIC, dez NUMERIC, total_ano NUMERIC)
LANGUAGE SQL STABLE AS $$
  SELECT c.id,c.sort_order,c.categoria,c.cod_referencia,COALESCE(c.label,MAX(s.descr_produto),c.cod_referencia),c.extra_data,
    SUM(CASE WHEN s.mes=1 THEN s.quantidade ELSE 0 END),SUM(CASE WHEN s.mes=2 THEN s.quantidade ELSE 0 END),SUM(CASE WHEN s.mes=3 THEN s.quantidade ELSE 0 END),SUM(CASE WHEN s.mes=4 THEN s.quantidade ELSE 0 END),
    SUM(CASE WHEN s.mes=5 THEN s.quantidade ELSE 0 END),SUM(CASE WHEN s.mes=6 THEN s.quantidade ELSE 0 END),SUM(CASE WHEN s.mes=7 THEN s.quantidade ELSE 0 END),SUM(CASE WHEN s.mes=8 THEN s.quantidade ELSE 0 END),
    SUM(CASE WHEN s.mes=9 THEN s.quantidade ELSE 0 END),SUM(CASE WHEN s.mes=10 THEN s.quantidade ELSE 0 END),SUM(CASE WHEN s.mes=11 THEN s.quantidade ELSE 0 END),SUM(CASE WHEN s.mes=12 THEN s.quantidade ELSE 0 END),SUM(COALESCE(s.quantidade,0))
  FROM report_config_items c
  JOIN sales_rows s ON s.cod_referencia = c.cod_referencia AND s.ano = p_ano
  WHERE c.report_key = 'geral'
    AND (p_cod_cliente IS NULL OR s.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code))
    AND (p_cod_referencia IS NULL OR s.cod_referencia = p_cod_referencia)
    AND (p_semestre IS NULL OR (p_semestre=1 AND s.mes BETWEEN 1 AND 6) OR (p_semestre=2 AND s.mes BETWEEN 7 AND 12))
    AND (p_descr_hist_financ IS NULL OR s.descr_hist_financ = p_descr_hist_financ)
  GROUP BY c.id,c.sort_order,c.categoria,c.cod_referencia,c.label,c.extra_data
  ORDER BY c.sort_order,c.categoria,c.cod_referencia;
$$;

-- Dashboard de cliente agregado: preserva o caminho otimizado da 0021 e
-- expande qualquer chave canônica para todos os códigos que a compõem.
CREATE OR REPLACE FUNCTION client_dashboard_summary(p_cod_cliente TEXT, p_ano INT)
RETURNS TABLE (
  periodo TEXT, ano INT, total_faturado NUMERIC, total_unidades NUMERIC,
  total_pedidos BIGINT, total_produtos BIGINT, meses_ativos INT,
  melhor_mes SMALLINT, ultimo_pedido DATE, faturamento_vitalicio NUMERIC,
  pedidos_vitalicios BIGINT, anos_ativos BIGINT
)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  ), base AS (
    SELECT
      sales.ano, sales.mes, sales.valor_total, sales.quantidade,
      sales.cod_referencia, sales.data_pedido,
      sales.user_id::TEXT || ':' || COALESCE(sales.data_pedido::TEXT, 'sem-data') || ':' ||
        COALESCE(NULLIF(TRIM(sales.codigo_pedido), ''), NULLIF(TRIM(sales.numero_pedido_talao), ''), NULLIF(TRIM(sales.pedido_cliente_opc), ''), sales.cod_referencia) AS order_key
    FROM sales_rows sales
    JOIN authorized_owners owner ON owner.user_id = sales.user_id
    WHERE sales.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code)
  ), vitalicio AS (
    SELECT COALESCE(SUM(base.valor_total), 0) AS faturamento_vitalicio,
      COUNT(DISTINCT base.order_key) AS pedidos_vitalicios,
      COUNT(DISTINCT base.ano) AS anos_ativos,
      MAX(base.data_pedido) AS ultimo_pedido
    FROM base
  ), por_periodo AS (
    SELECT base.ano,
      COALESCE(SUM(base.valor_total), 0) AS total_faturado,
      COALESCE(SUM(base.quantidade), 0) AS total_unidades,
      COUNT(DISTINCT base.order_key) AS total_pedidos,
      COUNT(DISTINCT base.cod_referencia) AS total_produtos,
      COUNT(DISTINCT CASE WHEN base.valor_total > 0 THEN base.mes END) AS meses_ativos
    FROM base WHERE base.ano IN (p_ano, p_ano - 1) GROUP BY base.ano
  ), mes_faturado AS (
    SELECT base.ano, base.mes, COALESCE(SUM(base.valor_total), 0) AS faturado_mes
    FROM base WHERE base.ano IN (p_ano, p_ano - 1) GROUP BY base.ano, base.mes
  ), melhor_mes_por_ano AS (
    SELECT DISTINCT ON (month_row.ano) month_row.ano, month_row.mes AS melhor_mes
    FROM mes_faturado month_row
    ORDER BY month_row.ano, month_row.faturado_mes DESC, month_row.mes
  )
  SELECT CASE WHEN period_row.ano = p_ano THEN 'current' ELSE 'previous' END,
    period_row.ano, period_row.total_faturado, period_row.total_unidades,
    period_row.total_pedidos, period_row.total_produtos,
    COALESCE(period_row.meses_ativos, 0)::INT,
    COALESCE(best_month.melhor_mes, 1)::SMALLINT,
    lifetime.ultimo_pedido, lifetime.faturamento_vitalicio,
    lifetime.pedidos_vitalicios, lifetime.anos_ativos
  FROM por_periodo period_row
  CROSS JOIN vitalicio lifetime
  LEFT JOIN melhor_mes_por_ano best_month ON best_month.ano = period_row.ano
  ORDER BY period_row.ano DESC;
$$;

CREATE OR REPLACE FUNCTION client_monthly_trend(p_cod_cliente TEXT, p_ano INT)
RETURNS TABLE (ano INT, mes SMALLINT, total_faturado NUMERIC, total_unidades NUMERIC, total_pedidos BIGINT)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  )
  SELECT sales.ano::INT, sales.mes,
    COALESCE(SUM(sales.valor_total), 0), COALESCE(SUM(sales.quantidade), 0),
    COUNT(DISTINCT sales.user_id::TEXT || ':' || COALESCE(sales.data_pedido::TEXT, 'sem-data') || ':' ||
      COALESCE(NULLIF(TRIM(sales.codigo_pedido), ''), NULLIF(TRIM(sales.numero_pedido_talao), ''), NULLIF(TRIM(sales.pedido_cliente_opc), ''), sales.cod_referencia))
  FROM sales_rows sales JOIN authorized_owners owner ON owner.user_id = sales.user_id
  WHERE sales.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code)
    AND sales.ano IN (p_ano, p_ano - 1)
  GROUP BY sales.ano, sales.mes ORDER BY sales.ano, sales.mes;
$$;

CREATE OR REPLACE FUNCTION client_yearly_history(p_cod_cliente TEXT)
RETURNS TABLE (ano INT, total_faturado NUMERIC, total_unidades NUMERIC, total_pedidos BIGINT, total_produtos BIGINT)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  )
  SELECT sales.ano::INT, COALESCE(SUM(sales.valor_total), 0), COALESCE(SUM(sales.quantidade), 0),
    COUNT(DISTINCT sales.user_id::TEXT || ':' || COALESCE(sales.data_pedido::TEXT, 'sem-data') || ':' ||
      COALESCE(NULLIF(TRIM(sales.codigo_pedido), ''), NULLIF(TRIM(sales.numero_pedido_talao), ''), NULLIF(TRIM(sales.pedido_cliente_opc), ''), sales.cod_referencia)),
    COUNT(DISTINCT sales.cod_referencia)
  FROM sales_rows sales JOIN authorized_owners owner ON owner.user_id = sales.user_id
  WHERE sales.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code)
  GROUP BY sales.ano ORDER BY sales.ano DESC;
$$;

CREATE OR REPLACE FUNCTION client_top_products(p_cod_cliente TEXT, p_ano INT, p_limit INT DEFAULT 50)
RETURNS TABLE (cod_referencia TEXT, descr_produto TEXT, ano INT, total_faturado NUMERIC, total_unidades NUMERIC, total_pedidos BIGINT, ultimo_pedido DATE)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  ), scoped AS (
    SELECT sales.cod_referencia, sales.descr_produto, sales.ano,
      sales.valor_total, sales.quantidade, sales.data_pedido,
      sales.user_id::TEXT || ':' || COALESCE(sales.data_pedido::TEXT, 'sem-data') || ':' ||
        COALESCE(NULLIF(TRIM(sales.codigo_pedido), ''), NULLIF(TRIM(sales.numero_pedido_talao), ''), NULLIF(TRIM(sales.pedido_cliente_opc), ''), sales.cod_referencia) AS order_key
    FROM sales_rows sales JOIN authorized_owners owner ON owner.user_id = sales.user_id
    WHERE sales.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code)
      AND sales.ano IN (p_ano, p_ano - 1)
  ), top_codes AS (
    SELECT scoped.cod_referencia
    FROM scoped
    GROUP BY scoped.cod_referencia
    ORDER BY SUM(scoped.valor_total) DESC
    LIMIT LEAST(GREATEST(COALESCE(p_limit, 50), 1), 100)
  )
  SELECT scoped.cod_referencia, MAX(scoped.descr_produto), scoped.ano::INT,
    COALESCE(SUM(scoped.valor_total), 0), COALESCE(SUM(scoped.quantidade), 0),
    COUNT(DISTINCT scoped.order_key), MAX(scoped.data_pedido)
  FROM scoped JOIN top_codes ON top_codes.cod_referencia = scoped.cod_referencia
  GROUP BY scoped.cod_referencia, scoped.ano
  ORDER BY scoped.ano DESC, SUM(scoped.valor_total) DESC;
$$;

CREATE OR REPLACE FUNCTION client_recent_orders(p_cod_cliente TEXT, p_limit INT DEFAULT 8)
RETURNS TABLE (codigo_pedido TEXT, data_pedido DATE, total_faturado NUMERIC, total_unidades NUMERIC, total_linhas BIGINT, produtos_destaque TEXT[])
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  ), lines AS (
    SELECT
      COALESCE(NULLIF(TRIM(sales.codigo_pedido), ''), NULLIF(TRIM(sales.numero_pedido_talao), ''), NULLIF(TRIM(sales.pedido_cliente_opc), '')) AS codigo_pedido,
      sales.user_id::TEXT || ':' || COALESCE(sales.data_pedido::TEXT, 'sem-data') || ':' ||
        COALESCE(NULLIF(TRIM(sales.codigo_pedido), ''), NULLIF(TRIM(sales.numero_pedido_talao), ''), NULLIF(TRIM(sales.pedido_cliente_opc), ''), sales.cod_referencia) AS order_key,
      sales.data_pedido, sales.valor_total, sales.quantidade, sales.descr_produto
    FROM sales_rows sales JOIN authorized_owners owner ON owner.user_id = sales.user_id
    WHERE sales.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code)
      AND sales.data_pedido IS NOT NULL
  ), grouped AS (
    SELECT MIN(lines.codigo_pedido) AS codigo_pedido,
      lines.order_key,
      MAX(lines.data_pedido) AS data_pedido,
      COALESCE(SUM(lines.valor_total), 0) AS total_faturado,
      COALESCE(SUM(lines.quantidade), 0) AS total_unidades,
      COUNT(*) AS total_linhas,
      (ARRAY_AGG(lines.descr_produto ORDER BY lines.valor_total DESC NULLS LAST))[1:2] AS produtos_destaque
    FROM lines GROUP BY lines.order_key
  )
  SELECT grouped.codigo_pedido, grouped.data_pedido, grouped.total_faturado,
    grouped.total_unidades, grouped.total_linhas, grouped.produtos_destaque
  FROM grouped
  ORDER BY grouped.data_pedido DESC NULLS LAST, grouped.order_key DESC
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 8), 1), 20);
$$;

REVOKE ALL ON FUNCTION client_dashboard_summary(TEXT, INT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION client_monthly_trend(TEXT, INT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION client_yearly_history(TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION client_top_products(TEXT, INT, INT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION client_recent_orders(TEXT, INT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION client_dashboard_summary(TEXT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION client_monthly_trend(TEXT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION client_yearly_history(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION client_top_products(TEXT, INT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION client_recent_orders(TEXT, INT) TO authenticated;

-- Ranking canônico usado na home.
CREATE OR REPLACE FUNCTION get_rep_ranking(p_ano INT DEFAULT NULL)
RETURNS TABLE (rep_id UUID, rep_email TEXT, total_faturado NUMERIC, total_pedidos BIGINT, num_clientes BIGINT)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  )
  SELECT sales.user_id, users.email, COALESCE(SUM(sales.valor_total), 0),
    COUNT(DISTINCT COALESCE(sales.data_pedido::TEXT, 'sem-data') || ':' ||
      COALESCE(NULLIF(TRIM(sales.codigo_pedido), ''), NULLIF(TRIM(sales.numero_pedido_talao), ''), NULLIF(TRIM(sales.pedido_cliente_opc), ''), sales.cod_referencia)),
    COUNT(DISTINCT COALESCE('group:' || member.group_id::TEXT, sales.cod_cliente))
  FROM sales_rows sales
  JOIN authorized_owners owner ON owner.user_id = sales.user_id
  JOIN auth.users users ON users.id = sales.user_id
  LEFT JOIN client_group_members member
    ON member.account_owner_id = current_account_owner_id() AND member.cod_cliente = sales.cod_cliente
  WHERE p_ano IS NULL OR sales.ano = p_ano
  GROUP BY sales.user_id, users.email
  ORDER BY SUM(sales.valor_total) DESC;
$$;

CREATE OR REPLACE FUNCTION get_client_ranking(p_ano INT DEFAULT NULL)
RETURNS TABLE (cod_cliente TEXT, nome_cliente TEXT, rep_email TEXT, total_faturado NUMERIC)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION
    SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  )
  SELECT
    COALESCE('group:' || group_row.id::TEXT, sales.cod_cliente),
    COALESCE(group_row.name, MAX(sales.nome_cliente)),
    CASE WHEN COUNT(DISTINCT users.email) = 1 THEN MAX(users.email) ELSE 'Equipe' END,
    SUM(sales.valor_total)
  FROM sales_rows sales
  JOIN authorized_owners owner ON owner.user_id = sales.user_id
  JOIN auth.users users ON users.id = sales.user_id
  LEFT JOIN client_group_members member
    ON member.account_owner_id = current_account_owner_id() AND member.cod_cliente = sales.cod_cliente
  LEFT JOIN client_groups group_row ON group_row.id = member.group_id
  WHERE p_ano IS NULL OR sales.ano = p_ano
  GROUP BY COALESCE('group:' || group_row.id::TEXT, sales.cod_cliente), group_row.id, group_row.name
  ORDER BY SUM(sales.valor_total) DESC;
$$;

REVOKE EXECUTE ON FUNCTION get_rep_ranking(INT) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION get_client_ranking(INT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION get_rep_ranking(INT) TO authenticated;
GRANT EXECUTE ON FUNCTION get_client_ranking(INT) TO authenticated;

CREATE OR REPLACE FUNCTION chat_resolve_client(p_query TEXT, p_limit INT DEFAULT 8)
RETURNS TABLE (cod_cliente TEXT, nome_cliente TEXT)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT result.cod_cliente, result.nome_cliente
  FROM search_clients(p_query, LEAST(COALESCE(p_limit, 8), 8), 0) result;
$$;

CREATE OR REPLACE FUNCTION chat_top_clients(p_ano INT, p_limit INT DEFAULT 10)
RETURNS TABLE (cod_cliente TEXT, nome_cliente TEXT, total_faturado NUMERIC, total_pedidos BIGINT)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION
    SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  )
  SELECT
    COALESCE('group:' || group_row.id::TEXT, sales.cod_cliente),
    COALESCE(group_row.name, MAX(sales.nome_cliente)),
    COALESCE(SUM(sales.valor_total), 0),
    COUNT(DISTINCT sales.user_id::TEXT || ':' || COALESCE(sales.data_pedido::TEXT, 'sem-data') || ':' || COALESCE(sales.codigo_pedido, sales.numero_pedido_talao, sales.pedido_cliente_opc, sales.cod_referencia))
  FROM sales_rows sales
  JOIN authorized_owners owner ON owner.user_id = sales.user_id
  LEFT JOIN client_group_members member
    ON member.account_owner_id = current_account_owner_id() AND member.cod_cliente = sales.cod_cliente
  LEFT JOIN client_groups group_row ON group_row.id = member.group_id
  WHERE sales.ano = p_ano
  GROUP BY COALESCE('group:' || group_row.id::TEXT, sales.cod_cliente), group_row.id, group_row.name
  ORDER BY SUM(sales.valor_total) DESC
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 10), 1), 20);
$$;

CREATE OR REPLACE FUNCTION chat_top_products(p_ano INT, p_cod_cliente TEXT DEFAULT NULL, p_semestre INT DEFAULT NULL, p_descr_hist_financ TEXT DEFAULT NULL, p_limit INT DEFAULT 10)
RETURNS TABLE (cod_referencia TEXT, descr_produto TEXT, total_faturado NUMERIC, total_unidades NUMERIC, total_pedidos BIGINT)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  )
  SELECT sales.cod_referencia, MAX(sales.descr_produto), COALESCE(SUM(sales.valor_total),0), COALESCE(SUM(sales.quantidade),0),
    COUNT(DISTINCT sales.user_id::TEXT || ':' || COALESCE(sales.data_pedido::TEXT, 'sem-data') || ':' || COALESCE(sales.codigo_pedido, sales.numero_pedido_talao, sales.pedido_cliente_opc, sales.cod_referencia))
  FROM sales_rows sales JOIN authorized_owners owner ON owner.user_id = sales.user_id
  WHERE sales.ano = p_ano
    AND (p_cod_cliente IS NULL OR sales.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code))
    AND (p_semestre IS NULL OR (p_semestre=1 AND sales.mes BETWEEN 1 AND 6) OR (p_semestre=2 AND sales.mes BETWEEN 7 AND 12))
    AND (p_descr_hist_financ IS NULL OR sales.descr_hist_financ = p_descr_hist_financ)
  GROUP BY sales.cod_referencia ORDER BY SUM(sales.valor_total) DESC
  LIMIT LEAST(GREATEST(COALESCE(p_limit,10),1),20);
$$;

CREATE OR REPLACE FUNCTION chat_sales_trend(p_start_year INT, p_end_year INT, p_cod_cliente TEXT DEFAULT NULL, p_cod_referencia TEXT DEFAULT NULL)
RETURNS TABLE (ano SMALLINT, mes SMALLINT, total_faturado NUMERIC, total_unidades NUMERIC, total_pedidos BIGINT)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  )
  SELECT sales.ano, sales.mes, COALESCE(SUM(sales.valor_total),0), COALESCE(SUM(sales.quantidade),0),
    COUNT(DISTINCT sales.user_id::TEXT || ':' || COALESCE(sales.data_pedido::TEXT, 'sem-data') || ':' || COALESCE(sales.codigo_pedido, sales.numero_pedido_talao, sales.pedido_cliente_opc, sales.cod_referencia))
  FROM sales_rows sales JOIN authorized_owners owner ON owner.user_id = sales.user_id
  WHERE sales.ano BETWEEN p_start_year AND p_end_year AND p_end_year >= p_start_year AND p_end_year-p_start_year <= 4
    AND (p_cod_cliente IS NULL OR sales.cod_cliente IN (SELECT code.cod_cliente FROM resolve_client_codes(p_cod_cliente) code))
    AND (p_cod_referencia IS NULL OR sales.cod_referencia = p_cod_referencia)
  GROUP BY sales.ano, sales.mes ORDER BY sales.ano, sales.mes;
$$;

CREATE OR REPLACE FUNCTION chat_inactive_clients(p_reference_date DATE, p_inactive_days INT DEFAULT 90, p_limit INT DEFAULT 10)
RETURNS TABLE (cod_cliente TEXT, nome_cliente TEXT, ultima_compra DATE, dias_sem_pedido INT, faturamento_historico NUMERIC, total_pedidos BIGINT)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  )
  SELECT COALESCE('group:' || group_row.id::TEXT, sales.cod_cliente),
    COALESCE(group_row.name, MAX(sales.nome_cliente)), MAX(sales.data_pedido),
    p_reference_date - MAX(sales.data_pedido), COALESCE(SUM(sales.valor_total), 0),
    COUNT(DISTINCT sales.user_id::TEXT || ':' || COALESCE(sales.data_pedido::TEXT, 'sem-data') || ':' ||
      COALESCE(NULLIF(TRIM(sales.codigo_pedido), ''), NULLIF(TRIM(sales.numero_pedido_talao), ''), NULLIF(TRIM(sales.pedido_cliente_opc), ''), sales.cod_referencia))
  FROM sales_rows sales
  JOIN authorized_owners owner ON owner.user_id = sales.user_id
  LEFT JOIN client_group_members member
    ON member.account_owner_id = current_account_owner_id() AND member.cod_cliente = sales.cod_cliente
  LEFT JOIN client_groups group_row ON group_row.id = member.group_id
  WHERE sales.data_pedido IS NOT NULL
  GROUP BY COALESCE('group:' || group_row.id::TEXT, sales.cod_cliente), group_row.id, group_row.name
  HAVING MAX(sales.data_pedido) <= p_reference_date - LEAST(GREATEST(COALESCE(p_inactive_days, 90), 1), 3650)
  ORDER BY p_reference_date - MAX(sales.data_pedido) DESC, SUM(sales.valor_total) DESC
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 10), 1), 20);
$$;

CREATE OR REPLACE FUNCTION chat_rep_performance(p_ano INT, p_limit INT DEFAULT 10)
RETURNS TABLE (rep_id UUID, rep_email TEXT, total_faturado NUMERIC, total_pedidos BIGINT, total_clientes BIGINT)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH authorized_owners AS (
    SELECT auth.uid() AS user_id
    UNION SELECT profile.id FROM profiles profile WHERE profile.leader_id = auth.uid()
  )
  SELECT sales.user_id, users.email, COALESCE(SUM(sales.valor_total), 0),
    COUNT(DISTINCT COALESCE(sales.data_pedido::TEXT, 'sem-data') || ':' ||
      COALESCE(NULLIF(TRIM(sales.codigo_pedido), ''), NULLIF(TRIM(sales.numero_pedido_talao), ''), NULLIF(TRIM(sales.pedido_cliente_opc), ''), sales.cod_referencia)),
    COUNT(DISTINCT COALESCE('group:' || member.group_id::TEXT, sales.cod_cliente))
  FROM sales_rows sales
  JOIN authorized_owners owner ON owner.user_id = sales.user_id
  JOIN auth.users users ON users.id = sales.user_id
  LEFT JOIN client_group_members member
    ON member.account_owner_id = current_account_owner_id() AND member.cod_cliente = sales.cod_cliente
  WHERE sales.ano = p_ano
  GROUP BY sales.user_id, users.email
  ORDER BY SUM(sales.valor_total) DESC, users.email
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 10), 1), 20);
$$;

REVOKE ALL ON FUNCTION chat_resolve_client(TEXT, INT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION chat_top_clients(INT, INT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION chat_top_products(INT, TEXT, INT, TEXT, INT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION chat_sales_trend(INT, INT, TEXT, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION chat_recent_orders(TEXT, INT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION chat_inactive_clients(DATE, INT, INT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION chat_rep_performance(INT, INT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION chat_resolve_client(TEXT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION chat_top_clients(INT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION chat_top_products(INT, TEXT, INT, TEXT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION chat_sales_trend(INT, INT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION chat_recent_orders(TEXT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION chat_inactive_clients(DATE, INT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION chat_rep_performance(INT, INT) TO authenticated;

-- Configuração efetiva: a linha do líder é a única lida pela conta.
-- Esta troca fica no fim da migration para reduzir o tempo de retenção do lock
-- forte exigido pelo DDL de políticas. Linhas históricas permanecem preservadas.
DROP POLICY IF EXISTS "saas_config_access" ON report_config_items;
DROP POLICY IF EXISTS "account_config_read" ON report_config_items;
DROP POLICY IF EXISTS "account_config_insert" ON report_config_items;
DROP POLICY IF EXISTS "account_config_update" ON report_config_items;
DROP POLICY IF EXISTS "account_config_delete" ON report_config_items;

CREATE POLICY account_config_read ON report_config_items
  FOR SELECT TO authenticated
  USING (user_id = current_account_owner_id());

CREATE POLICY account_config_insert ON report_config_items
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() AND is_current_account_leader());

CREATE POLICY account_config_update ON report_config_items
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid() AND is_current_account_leader())
  WITH CHECK (user_id = auth.uid() AND is_current_account_leader());

CREATE POLICY account_config_delete ON report_config_items
  FOR DELETE TO authenticated
  USING (user_id = auth.uid() AND is_current_account_leader());

NOTIFY pgrst, 'reload schema';
